import strawberryCake from "./assets/best sellers/strawberry cake.jpg";
import chocolate from "./assets/best sellers/chocolate.jpg";
import brownie from "./assets/best sellers/brownie.jpg";
export const PRODUCTS = [
  {
    key: 1,
    productName: "Chocolate Cake",
    price: 400,
    productImage: strawberryCake,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "cake",
  },
  {
    key: 2,
    productName: "Fruit Cake",
    price: 450,
    productImage: strawberryCake,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "cake",
  },
  {
    key: 3,
    productName: "Vanilla Cake",
    price: 350,
    productImage: strawberryCake,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "cake",
  },
  {
    key: 4,
    productName: "Dark Chocolate Cake",
    price: 450,
    productImage: strawberryCake,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "cake",
  },
  {
    key: 5,
    productName: "White Chocolate Cake",
    price: 450,
    productImage: strawberryCake,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "cake",
  },
  {
    key: 6,
    productName: "Chocolate brownie",
    price: 450,
    productImage: brownie,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "brownie",
  },
  {
    key: 7,
    productName: "Chocolate brownie",
    price: 450,
    productImage: brownie,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "brownie",
  },
  {
    key: 8,
    productName: "Chocolate brownie",
    price: 450,
    productImage: brownie,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "brownie",
  },
  {
    key: 9,
    productName: "Chocolate brownie",
    price: 450,
    productImage: brownie,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "brownie",
  },
  {
    key: 10,
    productName: "Chocolate brownie",
    price: 450,
    productImage: brownie,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "brownie",
  },
  {
    key: 11,
    productName: "Chocolate",
    price: 450,
    productImage: chocolate,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "chocolate",
  },
  {
    key: 12,
    productName: "Chocolate",
    price: 450,
    productImage: chocolate,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "chocolate",
  },
  {
    key: 13,
    productName: "Chocolate",
    price: 450,
    productImage: chocolate,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "chocolate",
  },
  {
    key: 14,
    productName: "Chocolate",
    price: 450,
    productImage: chocolate,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "chocolate",
  },
  {
    key: 15,
    productName: "Chocolate",
    price: 450,
    productImage: chocolate,
    about: "You’ve never tried a birthday cake like this. Our bestselling Birthday Cake, inspired by the boxed vanilla funfetti cake we loved as a kid, has grown up and gone gourmet. It has three tiers of heavenly rainbow-flecked vanilla birthday cake, layers of creamy frosting & crunchy crumbs, all topped with rainbow sprinkles.",
    type: "chocolate",
  },
];
